#!/bin/bash

wget https://github.com/spinicist/riesling/releases/download/v0.3/riesling-linux.tar.gz
tar xvzf riesling-linux.tar.gz
mkdir -p .local/bin
mv riesling .local/bin
ls -al .local/bin
echo $PATH
